### ISSUE TITLE
2024 update

### ISSUE THREAD

**Issue by berezovskyi** [theWebalyst/SPARQL-endpoints-lists#1]
Hello, Mark! Any chance the list can be updated for 2024? Or, alternatively, the methodology/scripts be published to redo it?

Right now, I got to fetching ca 500 endpoints (https://github.com/berezovskyi/sparqles/blob/main/endpoints_scraped.json) from the old Datahub API (https://github.com/berezovskyi/sparqles/blob/main/.github/workflows/scrape-sparql-endpoints.yml) but I think the data there has not been updated since 2019.

**Comment by happybeing** [comment]
Hi @berezovskyi and thanks for the interest. As you can see I've not touched this or VisLab for quite some time so I can't easily answer or provide the things you want. I'd have to resurrect VisLab first I think and then look at what it was doing. Hopefully everything would be apparent from that, but I have not plans for this.

Sorry I can't be of more help for now.

**Comment by berezovskyi** [comment]
Thanks for a quick reply, Mark!
